//Reddit Actions
export const MY_REDDIT_DATA_PENDING = 'MY_REDDIT_DATA_PENDING'
export const MY_REDDIT_DATA_ERROR = 'MY_REDDIT_DATA_ERROR'
export const MY_REDDIT_DATA_SUCCESS = 'MY_REDDIT_DATA_SUCCESS'
//Counter Actions
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
//Data Actions
export const DATA_AVAILABLE = 'DATA_AVAILABLE';